---
apiVersion: v1
kind: Secret
metadata:
  name: santhoshvernekar-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-aro24/santhoshvernekar-gateway-gitops
